### ISSUE TITLE
What to do when trying to lookup a $component that does ACCEPT_CONTEXT in $app scope

### ISSUE THREAD

**Issue by jjn1056** [perl-catalyst/catalyst-runtime#113]
AFAIK we never well defined what Myapp->component (->model, ->controller, ->view) should do.  We sometimes just say 'avoid it'.

But there seems to be legitimate cases when one wants to introspect a catalyst app (like for generating offline docs).

I'd like to define how this should work and what the limitations are:

 <jnap> but basically there's only three options I can see.  1) die or warn and skip when calling $app->componet($with_ACCEPT_CTX), 2) automatically mock $app to $ctx and proceed or 3) return the result of ->COMPONENT and expect the user to be smart enough to do the right thing
8:44 AM <jnap> or I guess we could say "You can never do $app->component...."
8:45 AM <jnap> I think its useful enough for introspection reasons to not do that.

**Comment by shadowcat-mst** [comment]
In the case of an app, ACCEPT_CONTEXT is passed $app.

Well behaved ACCEPT_CONTEXT methods, like the one in Catalyst::Component::InstancePerContext, already handle this fine.

None of your three options are necessary; the existing behaviour is correct, more general, and supports a significant amount of code that would be broken by any of those changes.

Note that, effectively (3) is what well-behaved ACCEPT_CONTEXT methods *normally* do, themselves, but this is not strictly required and I don't see us gaining anything by restricting it.

**Comment by jjn1056** [comment]
<@mst> jnap: that it may be passed $app or $c and should handle both cases, and that 'usually' 'return $self unless ref($c);' is the right thing
9:12 AM <jnap> I'll need to add that to https://metacpan.org/release/Catalyst-Plugin-InjectionHelpers as well then (and maybe a role in that distribution that does the right thing automatically for people to consume

**Comment by jjn1056** [comment]
Update:: We added docs to Catalyst::Component to make it clear you  must when doing ACCEPT_CONTEXT handle the $app case.  I reviewed Catalyst-Plugin-InjectionHelpers and see no code updates required so closing.
