### ISSUE TITLE
Behavior of $c->state inside $c->execute differs significantly from documentation

### ISSUE THREAD

**Issue by cventers** [perl-catalyst/catalyst-runtime#136]
Note: I was asked by JJNAPIORK to open this issue here instead of RT.

Commit e459bd036c9076bd7301ea2fbdd5d4ba9900ddf0 to Catalyst::Runtime introduced a regression to our Catalyst code bases.

We use a controller action, "authenticate" to check authentication credentials on web service endpoints called on our app. Because the behavior of $c->forward() is to wrap the action in eval { }, we followed the advice in the documentation to call $c->forward like this:

$c->forward('authenticate') || return;

This used to work just fine. Unfortunately, after the aforementioned commit, $c->state() is not set to 0. The line(s) setting $c->state to 0 are commented out in that commit along with the message "preserve $c->state".

The unfortunate effect of this is that if we throw an exception inside our authenticate action, it is now short circuiting and allowing control flow to continue, despite our exception.

For now, we resolved the issue by returning if $c->has_errors but it seems that this commit should either be reverted, or the documentation updated to reflect the fact that checking the $c->forward() return value is no longer a reliable way to handle exceptions.

**Comment by cventers** [comment]
The documentation I am referring to is the Catalyst.pm documentation for the $c->forward() method, which reads in part:

> If you want die to propagate you need to do something like:
>
>    $c->forward('foo');
>    die join "\n", @{ $c->error } if @{ $c->error };
>
> **Or make sure to always return true values from your actions and write your code like this:**
>
>    $c->forward('foo') || return;

We always followed the second recommendation in our code base. Last step for a successful authentication action was to return 1. Since that technique was specifically recommended as a way to propagate die, we assumed it was safe. It was in fact safe for some time. As mentioned, Catalyst *used* to clear $c->state to false inside $c->forward, until the change above was introduced which altered that behavior.

Maybe I misunderstood the documentation? In any case I feel that it is unclear and I may not be the only one caught off guard by the change. Thoughts appreciated.

**Comment by jjn1056** [comment]
so from the docs:

https://metacpan.org/pod/Catalyst#c-state

its clear that when there's an exception, state should become 0.  I'm going to change 'generally' to always in that doc.

So bug accepted, and I'll check it out since I created the bug.

**Comment by jjn1056** [comment]
hey, I might have time to look at this this week.  It would really help if there was a test case I could code against.  You should be able to modify this one:

https://metacpan.org/source/JJNAPIORK/Catalyst-Runtime-5.90104/t/state.t

to cause the error.  it would save me some time and increase the likelihood I'd get this fixed this week

**Comment by jjn1056** [comment]
OK so this hopefully is fixed in 5.90105 that I just released this hour.  Let me know if its good and we can close this issue.

**Comment by cventers** [comment]
Seems to work just fine now. Thanks!
