### ISSUE TITLE
Debug output does not show multiple parameters with Hash::MultiValue

### ISSUE THREAD

**Issue by tremor69** [perl-catalyst/catalyst-runtime#149]
It seems to me that the default debug output of the development server does not show parameters that appear multiple times correctly when `use_hash_multivalue_in_request` is switched on.

Unfortunately I cannot find the location in the code where this debug output is generated or I would try to provide a fix. But maybe I have made some mistake and this is not at all a bug.

Request:
`/test?attribute-25=opt1&attribute-25=opt2&attribute-25=opt3`

Output:
```
Body Parameters are:
.-------------------------------------+-------------------------------------------------.
| Parameter                           | Value                                           |
+-------------------------------------+-------------------------------------------------+
| attribute-25                        | opt3                                            |
'-------------------------------------+-------------------------------------------------'
```

Expected:
```
Body Parameters are:
.-------------------------------------+-------------------------------------------------.
| Parameter                           | Value                                           |
+-------------------------------------+-------------------------------------------------+
| attribute-25  (multiple)            | opt1, opt2, opt3                                |
'-------------------------------------+-------------------------------------------------'
```

**Comment by perl-catalyst-sync** [comment]
I think this is a good catch.  Any chance you can help write a test code
for this?  I'm pretty sure I can fix it.  -jnap

**Comment by tremor69** [comment]
I think it is actually easier for me to fix it if you can point me to the place/file/sub where this debug output is generated.

**Comment by tremor69** [comment]
Just found it. I will try to prepare a pull request.
