### ISSUE TITLE
Remove Test::Aggregator

### ISSUE THREAD

**Issue by jhannah** [perl-catalyst/catalyst-runtime#159]
A fresh install of Catalyst author deps on perl 5.26.1 is mad:
```
cpanm --installdeps --with-develop .
...
Test::Aggregate:   Bailout called.  Further testing stopped:  This module only works with
                 Test::More version < 1.3, but you have 1.302073.
```
IRC #catalyst-dev says:
23:40 < jhannah> looks like Makefile.PL line 103 is already hedging the bets on these libs :/
23:41 < jhannah> thanks @rafl 2010 :)
23:48 < @haarg> Test::Aggregate is unlikely to ever be fixed
23:48 < haarg> it should probably be stripped out of Catalyst
23:49 < @jjn1056 > we probably should have pulled it a long time ago
23:50 < jnap> in theory it makes tests run faster, I think that's all it does.  but it was never
              picked up popularity wise
23:50 < jnap> https://metacpan.org/requires/module/Test::Aggregate?sort=[[2,1]]&size=500
23:52 < jnap> so ideally we should remove TA and possible refactor the makefile a bit I guess

So strip it out.

**Comment by haarg** [comment]
This was done in 5.90116
