### ISSUE TITLE
Passing fragment as reference to uri_for generates #SCALAR(...)

### ISSUE THREAD

**Issue by sjohnston** [perl-catalyst/catalyst-runtime#160]
When $path is an unblessed string, $fragment does not get dereferenced. Failing test:

`is(
    Catalyst::uri_for( $context, '/bar', { param1 => 'value1' }, \'fragment' )->as_string,
    'http://127.0.0.1/foo/bar?param1=value1#fragment',
    'URI for path with fragment and query params 1'
);`

PR incoming.

**Comment by haarg** [comment]
Fixed in 0cdca4d84f1a6afca5fd00b3fdff611b4ec505d4, tests in 3662b13ee87e5dc4f2929b6c6f25bf9aa6565c86.
